declare meiro{
   input map_value_arg0[BIT],map_value_arg1[BIT],map_value_arg2[BIT],map_value_arg3[BIT],map_value_arg4[BIT],map_value_arg5[BIT],map_value_arg6[BIT],map_value_arg7[BIT],map_value_arg8[BIT],map_value_arg9[BIT]
                  ,map_value_arg10[BIT],map_value_arg11[BIT],map_value_arg12[BIT],map_value_arg13[BIT],map_value_arg14[BIT],map_value_arg15[BIT],map_value_arg16[BIT],map_value_arg17[BIT],map_value_arg18[BIT],map_value_arg19[BIT]
                  ,map_value_arg20[BIT],map_value_arg21[BIT],map_value_arg22[BIT],map_value_arg23[BIT],map_value_arg24[BIT],map_value_arg25[BIT],map_value_arg26[BIT],map_value_arg27[BIT],map_value_arg28[BIT],map_value_arg29[BIT]
                  ,map_value_arg30[BIT],map_value_arg31[BIT],map_value_arg32[BIT],map_value_arg33[BIT],map_value_arg34[BIT],map_value_arg35[BIT],map_value_arg36[BIT],map_value_arg37[BIT],map_value_arg38[BIT],map_value_arg39[BIT]
                  ,map_value_arg40[BIT],map_value_arg41[BIT],map_value_arg42[BIT],map_value_arg43[BIT],map_value_arg44[BIT],map_value_arg45[BIT],map_value_arg46[BIT],map_value_arg47[BIT],map_value_arg48[BIT],map_value_arg49[BIT]
                  ,map_value_arg50[BIT],map_value_arg51[BIT],map_value_arg52[BIT],map_value_arg53[BIT],map_value_arg54[BIT],map_value_arg55[BIT],map_value_arg56[BIT],map_value_arg57[BIT],map_value_arg58[BIT],map_value_arg59[BIT]
                  ,map_value_arg60[BIT],map_value_arg61[BIT],map_value_arg62[BIT],map_value_arg63[BIT],map_value_arg64[BIT],map_value_arg65[BIT],map_value_arg66[BIT],map_value_arg67[BIT],map_value_arg68[BIT],map_value_arg69[BIT]
                  ,map_value_arg70[BIT],map_value_arg71[BIT],map_value_arg72[BIT],map_value_arg73[BIT],map_value_arg74[BIT],map_value_arg75[BIT],map_value_arg76[BIT],map_value_arg77[BIT],map_value_arg78[BIT],map_value_arg79[BIT]
                  ,map_value_arg80[BIT],map_value_arg81[BIT],map_value_arg82[BIT],map_value_arg83[BIT],map_value_arg84[BIT],map_value_arg85[BIT],map_value_arg86[BIT],map_value_arg87[BIT],map_value_arg88[BIT],map_value_arg89[BIT]
                 , map_value_arg90[BIT],map_value_arg91[BIT],map_value_arg92[BIT],map_value_arg93[BIT],map_value_arg94[BIT],map_value_arg95[BIT],map_value_arg96[BIT],map_value_arg97[BIT],map_value_arg98[BIT],map_value_arg99[BIT]
                 , map_value_arg100[BIT],map_value_arg101[BIT],map_value_arg102[BIT],map_value_arg103[BIT],map_value_arg104[BIT],map_value_arg105[BIT],map_value_arg106[BIT],map_value_arg107[BIT],map_value_arg108[BIT],map_value_arg109[BIT]
                 , map_value_arg110[BIT],map_value_arg111[BIT],map_value_arg112[BIT],map_value_arg113[BIT],map_value_arg114[BIT],map_value_arg115[BIT],map_value_arg116[BIT],map_value_arg117[BIT],map_value_arg118[BIT],map_value_arg119[BIT]
                 , map_value_arg120[BIT],map_value_arg121[BIT],map_value_arg122[BIT],map_value_arg123[BIT],map_value_arg124[BIT],map_value_arg125[BIT],map_value_arg126[BIT],map_value_arg127[BIT],map_value_arg128[BIT],map_value_arg129[BIT]
                 , map_value_arg130[BIT],map_value_arg131[BIT],map_value_arg132[BIT],map_value_arg133[BIT],map_value_arg134[BIT],map_value_arg135[BIT],map_value_arg136[BIT],map_value_arg137[BIT],map_value_arg138[BIT],map_value_arg139[BIT]
                 , map_value_arg140[BIT],map_value_arg141[BIT],map_value_arg142[BIT],map_value_arg143[BIT],map_value_arg144[BIT],map_value_arg145[BIT],map_value_arg146[BIT],map_value_arg147[BIT],map_value_arg148[BIT],map_value_arg149[BIT]
                 , map_value_arg150[BIT],map_value_arg151[BIT],map_value_arg152[BIT],map_value_arg153[BIT],map_value_arg154[BIT],map_value_arg155[BIT],map_value_arg156[BIT],map_value_arg157[BIT],map_value_arg158[BIT],map_value_arg159[BIT]
                 , map_value_arg160[BIT],map_value_arg161[BIT],map_value_arg162[BIT],map_value_arg163[BIT],map_value_arg164[BIT],map_value_arg165[BIT],map_value_arg166[BIT],map_value_arg167[BIT],map_value_arg168[BIT],map_value_arg169[BIT]
                 , map_value_arg170[BIT],map_value_arg171[BIT],map_value_arg172[BIT],map_value_arg173[BIT],map_value_arg174[BIT],map_value_arg175[BIT],map_value_arg176[BIT],map_value_arg177[BIT],map_value_arg178[BIT],map_value_arg179[BIT]
                 , map_value_arg180[BIT],map_value_arg181[BIT],map_value_arg182[BIT],map_value_arg183[BIT],map_value_arg184[BIT],map_value_arg185[BIT],map_value_arg186[BIT],map_value_arg187[BIT],map_value_arg188[BIT],map_value_arg189[BIT]
                 , map_value_arg190[BIT],map_value_arg191[BIT],map_value_arg192[BIT],map_value_arg193[BIT],map_value_arg194[BIT],map_value_arg195[BIT],map_value_arg196[BIT],map_value_arg197[BIT],map_value_arg198[BIT],map_value_arg199[BIT]
                 , map_value_arg200[BIT],map_value_arg201[BIT],map_value_arg202[BIT],map_value_arg203[BIT],map_value_arg204[BIT],map_value_arg205[BIT],map_value_arg206[BIT],map_value_arg207[BIT],map_value_arg208[BIT],map_value_arg209[BIT]
                 , map_value_arg210[BIT],map_value_arg211[BIT],map_value_arg212[BIT],map_value_arg213[BIT],map_value_arg214[BIT],map_value_arg215[BIT],map_value_arg216[BIT],map_value_arg217[BIT],map_value_arg218[BIT],map_value_arg219[BIT]
                 , map_value_arg220[BIT],map_value_arg221[BIT],map_value_arg222[BIT],map_value_arg223[BIT],map_value_arg224[BIT],map_value_arg225[BIT],map_value_arg226[BIT],map_value_arg227[BIT],map_value_arg228[BIT],map_value_arg229[BIT]
                 , map_value_arg230[BIT],map_value_arg231[BIT],map_value_arg232[BIT],map_value_arg233[BIT],map_value_arg234[BIT],map_value_arg235[BIT],map_value_arg236[BIT],map_value_arg237[BIT],map_value_arg238[BIT],map_value_arg239[BIT]
                 , map_value_arg240[BIT],map_value_arg241[BIT],map_value_arg242[BIT],map_value_arg243[BIT],map_value_arg244[BIT],map_value_arg245[BIT],map_value_arg246[BIT],map_value_arg247[BIT],map_value_arg248[BIT],map_value_arg249[BIT]
                 , map_value_arg250[BIT],map_value_arg251[BIT],map_value_arg252[BIT],map_value_arg253[BIT],map_value_arg254[BIT],map_value_arg255[BIT];
   output  kekka_out0[BIT],kekka_out1[BIT],kekka_out2[BIT],kekka_out3[BIT],kekka_out4[BIT],kekka_out5[BIT],kekka_out6[BIT],kekka_out7[BIT],kekka_out8[BIT],kekka_out9[BIT],
                     kekka_out10[BIT],kekka_out11[BIT],kekka_out12[BIT],kekka_out13[BIT],kekka_out14[BIT],kekka_out15[BIT],kekka_out16[BIT],kekka_out17[BIT],kekka_out18[BIT],kekka_out19[BIT],
                     kekka_out20[BIT],kekka_out21[BIT],kekka_out22[BIT],kekka_out23[BIT],kekka_out24[BIT],kekka_out25[BIT],kekka_out26[BIT],kekka_out27[BIT],kekka_out28[BIT],kekka_out29[BIT],
                     kekka_out30[BIT],kekka_out31[BIT],kekka_out32[BIT],kekka_out33[BIT],kekka_out34[BIT],kekka_out35[BIT],kekka_out36[BIT],kekka_out37[BIT],kekka_out38[BIT],kekka_out39[BIT],
                     kekka_out40[BIT],kekka_out41[BIT],kekka_out42[BIT],kekka_out43[BIT],kekka_out44[BIT],kekka_out45[BIT],kekka_out46[BIT],kekka_out47[BIT],kekka_out48[BIT],kekka_out49[BIT],
                     kekka_out50[BIT],kekka_out51[BIT],kekka_out52[BIT],kekka_out53[BIT],kekka_out54[BIT],kekka_out55[BIT],kekka_out56[BIT],kekka_out57[BIT],kekka_out58[BIT],kekka_out59[BIT],
                     kekka_out60[BIT],kekka_out61[BIT],kekka_out62[BIT],kekka_out63[BIT],kekka_out64[BIT],kekka_out65[BIT],kekka_out66[BIT],kekka_out67[BIT],kekka_out68[BIT],kekka_out69[BIT],
                     kekka_out70[BIT],kekka_out71[BIT],kekka_out72[BIT],kekka_out73[BIT],kekka_out74[BIT],kekka_out75[BIT],kekka_out76[BIT],kekka_out77[BIT],kekka_out78[BIT],kekka_out79[BIT],
                     kekka_out80[BIT],kekka_out81[BIT],kekka_out82[BIT],kekka_out83[BIT],kekka_out84[BIT],kekka_out85[BIT],kekka_out86[BIT],kekka_out87[BIT],kekka_out88[BIT],kekka_out89[BIT],
                     kekka_out90[BIT],kekka_out91[BIT],kekka_out92[BIT],kekka_out93[BIT],kekka_out94[BIT],kekka_out95[BIT],kekka_out96[BIT],kekka_out97[BIT],kekka_out98[BIT],kekka_out99[BIT],
                     kekka_out100[BIT],kekka_out101[BIT],kekka_out102[BIT],kekka_out103[BIT],kekka_out104[BIT],kekka_out105[BIT],kekka_out106[BIT],kekka_out107[BIT],kekka_out108[BIT],kekka_out109[BIT],
                     kekka_out110[BIT]
                    ;
   func_in in_do(map_value_arg0,map_value_arg1,map_value_arg2,map_value_arg3,map_value_arg4,map_value_arg5,map_value_arg6,map_value_arg7,map_value_arg8,map_value_arg9,
                  map_value_arg10,map_value_arg11,map_value_arg12,map_value_arg13,map_value_arg14,map_value_arg15,map_value_arg16,map_value_arg17,map_value_arg18,map_value_arg19,
                  map_value_arg20,map_value_arg21,map_value_arg22,map_value_arg23,map_value_arg24,map_value_arg25,map_value_arg26,map_value_arg27,map_value_arg28,map_value_arg29,
                  map_value_arg30,map_value_arg31,map_value_arg32,map_value_arg33,map_value_arg34,map_value_arg35,map_value_arg36,map_value_arg37,map_value_arg38,map_value_arg39,
                  map_value_arg40,map_value_arg41,map_value_arg42,map_value_arg43,map_value_arg44,map_value_arg45,map_value_arg46,map_value_arg47,map_value_arg48,map_value_arg49,
                  map_value_arg50,map_value_arg51,map_value_arg52,map_value_arg53,map_value_arg54,map_value_arg55,map_value_arg56,map_value_arg57,map_value_arg58,map_value_arg59,
                  map_value_arg60,map_value_arg61,map_value_arg62,map_value_arg63,map_value_arg64,map_value_arg65,map_value_arg66,map_value_arg67,map_value_arg68,map_value_arg69,
                  map_value_arg70,map_value_arg71,map_value_arg72,map_value_arg73,map_value_arg74,map_value_arg75,map_value_arg76,map_value_arg77,map_value_arg78,map_value_arg79,
                  map_value_arg80,map_value_arg81,map_value_arg82,map_value_arg83,map_value_arg84,map_value_arg85,map_value_arg86,map_value_arg87,map_value_arg88,map_value_arg89,
                  map_value_arg90,map_value_arg91,map_value_arg92,map_value_arg93,map_value_arg94,map_value_arg95,map_value_arg96,map_value_arg97,map_value_arg98,map_value_arg99,
                  map_value_arg100,map_value_arg101,map_value_arg102,map_value_arg103,map_value_arg104,map_value_arg105,map_value_arg106,map_value_arg107,map_value_arg108,map_value_arg109,
                  map_value_arg110,map_value_arg111,map_value_arg112,map_value_arg113,map_value_arg114,map_value_arg115,map_value_arg116,map_value_arg117,map_value_arg118,map_value_arg119,
                  map_value_arg120,map_value_arg121,map_value_arg122,map_value_arg123,map_value_arg124,map_value_arg125,map_value_arg126,map_value_arg127,map_value_arg128,map_value_arg129,
                  map_value_arg130,map_value_arg131,map_value_arg132,map_value_arg133,map_value_arg134,map_value_arg135,map_value_arg136,map_value_arg137,map_value_arg138,map_value_arg139,
                  map_value_arg140,map_value_arg141,map_value_arg142,map_value_arg143,map_value_arg144,map_value_arg145,map_value_arg146,map_value_arg147,map_value_arg148,map_value_arg149,
                  map_value_arg150,map_value_arg151,map_value_arg152,map_value_arg153,map_value_arg154,map_value_arg155,map_value_arg156,map_value_arg157,map_value_arg158,map_value_arg159,
                  map_value_arg160,map_value_arg161,map_value_arg162,map_value_arg163,map_value_arg164,map_value_arg165,map_value_arg166,map_value_arg167,map_value_arg168,map_value_arg169,
                  map_value_arg170,map_value_arg171,map_value_arg172,map_value_arg173,map_value_arg174,map_value_arg175,map_value_arg176,map_value_arg177,map_value_arg178,map_value_arg179,
                  map_value_arg180,map_value_arg181,map_value_arg182,map_value_arg183,map_value_arg184,map_value_arg185,map_value_arg186,map_value_arg187,map_value_arg188,map_value_arg189,
                  map_value_arg190,map_value_arg191,map_value_arg192,map_value_arg193,map_value_arg194,map_value_arg195,map_value_arg196,map_value_arg197,map_value_arg198,map_value_arg199,
                  map_value_arg200,map_value_arg201,map_value_arg202,map_value_arg203,map_value_arg204,map_value_arg205,map_value_arg206,map_value_arg207,map_value_arg208,map_value_arg209,
                  map_value_arg210,map_value_arg211,map_value_arg212,map_value_arg213,map_value_arg214,map_value_arg215,map_value_arg216,map_value_arg217,map_value_arg218,map_value_arg219,
                  map_value_arg220,map_value_arg221,map_value_arg222,map_value_arg223,map_value_arg224,map_value_arg225,map_value_arg226,map_value_arg227,map_value_arg228,map_value_arg229,
                  map_value_arg230,map_value_arg231,map_value_arg232,map_value_arg233,map_value_arg234,map_value_arg235,map_value_arg236,map_value_arg237,map_value_arg238,map_value_arg239,
                  map_value_arg240,map_value_arg241,map_value_arg242,map_value_arg243,map_value_arg244,map_value_arg245,map_value_arg246,map_value_arg247,map_value_arg248,map_value_arg249,
                  map_value_arg250,map_value_arg251,map_value_arg252,map_value_arg253,map_value_arg254,map_value_arg255);
   func_out end_meiro(kekka_out0,kekka_out1,kekka_out2,kekka_out3,kekka_out4,kekka_out5,kekka_out6,kekka_out7,kekka_out8,kekka_out9,
                     kekka_out10,kekka_out11,kekka_out12,kekka_out13,kekka_out14,kekka_out15,kekka_out16,kekka_out17,kekka_out18,kekka_out19,
                     kekka_out20,kekka_out21,kekka_out22,kekka_out23,kekka_out24,kekka_out25,kekka_out26,kekka_out27,kekka_out28,kekka_out29,
                     kekka_out30,kekka_out31,kekka_out32,kekka_out33,kekka_out34,kekka_out35,kekka_out36,kekka_out37,kekka_out38,kekka_out39,
                     kekka_out40,kekka_out41,kekka_out42,kekka_out43,kekka_out44,kekka_out45,kekka_out46,kekka_out47,kekka_out48,kekka_out49,
                     kekka_out50,kekka_out51,kekka_out52,kekka_out53,kekka_out54,kekka_out55,kekka_out56,kekka_out57,kekka_out58,kekka_out59,
                     kekka_out60,kekka_out61,kekka_out62,kekka_out63,kekka_out64,kekka_out65,kekka_out66,kekka_out67,kekka_out68,kekka_out69,
                     kekka_out70,kekka_out71,kekka_out72,kekka_out73,kekka_out74,kekka_out75,kekka_out76,kekka_out77,kekka_out78,kekka_out79,
                     kekka_out80,kekka_out81,kekka_out82,kekka_out83,kekka_out84,kekka_out85,kekka_out86,kekka_out87,kekka_out88,kekka_out89,
                     kekka_out90,kekka_out91,kekka_out92,kekka_out93,kekka_out94,kekka_out95,kekka_out96,kekka_out97,kekka_out98,kekka_out99,
                     kekka_out100,kekka_out101,kekka_out102,kekka_out103,kekka_out104,kekka_out105,kekka_out106,kekka_out107,kekka_out108,kekka_out109,
                     kekka_out110
                     );

    }
